export const personal = {
  name: 'Bagus Mukti Purnomo',
  role: 'Software Engineer',
  location: 'Surabaya, East Java',
  email: 'bagusmuktipurnomo@gmail.com',
  github: 'https://github.com/bagusmukti',
  linkedin: 'https://www.linkedin.com/in/bagusmuktipurnomo',
  photo: '/profil.jpeg',
  bio: `A passionate Software Engineer with about 2 years of experience in web and mobile application development. Experienced in leading development teams as a Product Owner. With experience spanning front end, back end, and mobile development, I leverage modern technologies such as React, Laravel, ASP.NET and Flutter to create scalable, user centered, and impactful digital products. Beyond technical expertise, my experience as a Product Owner has strengthened my ability to lead teams and bridge the gap between innovative ideas and practical solutions. I thrive on turning complex challenges into elegant, scalable, and user focused applications that make a real difference. Driven by a passion for building exceptional digital experiences, I enjoy transforming ideas into elegant, functional, and high quality applications that deliver meaningful value to users.`,
  chips: ['Systems thinker', 'Detail oriented', 'Clean code', 'Team player', 'Fast learner'],
}

export const skills = [
  { cat: 'Frontend', tags: ['Javascript', 'React', 'TypeScript', 'Tailwind CSS'], level: 'Advanced' },
  { cat: 'Backend',  tags: ['PHP', 'C#', 'Laravel', 'ASP.NET'],                  level: 'Advanced' },
  { cat: 'Mobile',   tags: ['Flutter', 'Dart', 'BLoC', 'Provider'],               level: 'Intermediate' },
  { cat: 'Database', tags: ['MySQL', 'PostgreSQL', 'Redis'],                       level: 'Proficient' },
  { cat: 'Workflow', tags: ['Git', 'CI/CD', 'Figma', 'Agile'],                    level: 'Everyday' },
]

export const projects = [
  {
    num: '01',
    title: 'BudgEx',
    stack: ['Flutter', 'React Typescript', 'ASP.NET'],
    star: {
      situation: 'Finance teams struggled to monitor budget realization across departments without a unified real-time system.',
      task: 'Build a cross-platform budget planning and control platform covering planning, realization tracking, and variance analysis.',
      action: 'Developed a Flutter mobile app, React TypeScript dashboard, and ASP.NET REST API with role-based access and department-level data isolation.',
      result: 'Delivered a centralized financial management solution that streamlined budget oversight and improved visibility into departmental spending and budget utilization.',
    },
    year: '2026',
    color: 'ind',
    githubUrl: '#',
    image: '',
  },
  {
    num: '02',
    title: 'DataKita',
    stack: ['React', 'Typescript', 'Tailwind'],
    star: {
      situation: 'Public data from BMKG, World Bank, and disease.sh was scattered across APIs with no accessible unified view for the general public.',
      task: 'Create an open data dashboard that aggregates multiple public APIs and presents them as interactive visualizations.',
      action: 'Built a React TypeScript SPA with Tailwind, integrated 3 public APIs, and implemented chart components using Recharts with responsive layouts.',
      result: 'Dashboard covers weather, economic, and health data in one place; received positive feedback from peers for usability and visual clarity.',
    },
    year: '2026',
    color: 'pch',
    githubUrl: 'https://github.com/bagusmukti/datakita',
    image: '',
  },
  {
    num: '03',
    title: 'RoomRes',
    stack: ['ASP.NET', 'React Typescript', 'PostgreSQL'],
    star: {
      situation: 'Campus room booking was handled manually via physical forms, causing scheduling conflicts and slow approval turnaround.',
      task: 'Design and build a web-based room reservation system with real-time schedule visibility and status tracking.',
      action: 'Built an ASP.NET Core API with PostgreSQL, a React TypeScript frontend, and an admin panel for managing room availability and booking requests.',
      result: 'Provided a centralized room booking workflow that improved scheduling visibility and streamlined reservation management across campus facilities.',
    },
    year: '2026',
    color: 'lav',
    githubUrl: 'https://github.com/bagusmukti/2026-room-reservation-frontend',
    image: '',
  },
  {
    num: '04',
    title: 'Employee Management System',
    stack: ['Laravel', 'PHP', 'Javascript'],
    star: {
      situation: 'Managing employee records, attendance, and leave requests through separate processes can increase administrative workload and reduce operational efficiency.',
      task: 'Build a full workforce management platform covering employee records, attendance, leave, and admin operations — solo, in 3 months.',
      action: 'Developed with Laravel and JavaScript; designed a normalized MySQL schema and integrated a fingerprint attendance module via REST API.',
      result: 'Digitized key HR processes through a centralized platform, improving accessibility and organization of workforce data.',
    },
    year: '2025',
    color: 'mint',
    githubUrl: 'https://github.com/bagusmukti/app-pegawai',
    image: '',
  },
  {
    num: '05',
    title: 'Local MSMEs',
    stack: ['React', 'Tailwind CSS', 'Supabase'],
    star: {
      situation: 'Local MSMEs in the area had no digital presence, making it difficult for customers to discover or contact them.',
      task: 'Build a directory platform to help users find local businesses through category browsing and location-based search.',
      action: 'Built with React, Tailwind CSS, and Supabase for auth and data; implemented map integration and category filtering with real-time search.',
      result: 'Provided a centralized directory that improved business discoverability and simplified access to local products and services.',
    },
    year: '2025',
    color: 'lav',
    githubUrl: 'https://github.com/bagusmukti/umkm-lokal',
    image: '',
  },
  {
    num: '06',
    title: 'Public Grievance System',
    stack: ['PHP', 'Javascript', 'CSS'],
    star: {
      situation: 'Citizens had no structured way to report public service issues — complaints were submitted verbally and often went untracked.',
      task: 'Build a citizen complaint platform where users can submit reports, track status, and receive responses from administrators.',
      action: 'Developed with PHP, JS, and CSS; built an admin panel for complaint triage, status updates, and response management.',
      result: 'Digitized the full complaint lifecycle; admin response rate improved significantly with centralized tracking replacing manual logs.',
    },
    year: '2025',
    color: 'pch',
    githubUrl: 'https://github.com/bagusmukti/Project-UAS',
    image: '',
  },
]