export const personal = {
  name: 'Bagus Mukti Purnomo',
  role: 'Software Engineer',
  location: 'Surabaya, East Java',
  email: 'bagusmuktipurnomo@gmail.com',
  github: 'https://github.com/bagusmukti',
  linkedin: 'https://www.linkedin.com/in/bagusmuktipurnomo',
  instagram: 'https://www.instagram.com/bagusmuktiii/',
  photo: '/src/assets/profil.jpeg',
  bio: `A passionate Software Engineer with about 2 years of experience in web and mobile application development. Experienced in leading development teams as a Product Owner. With experience spanning front end, back end, and mobile development, I leverage modern technologies such as React, Laravel, ASP.NET and Flutter to create scalable, user centered, and impactful digital products. Beyond technical expertise, my experience as a Product Owner has strengthened my ability to lead teams and bridge the gap between innovative ideas and practical solutions. I thrive on turning complex challenges into elegant, scalable, and user focused applications that make a real difference. Driven by a passion for building exceptional digital experiences, I enjoy transforming ideas into elegant, functional, and high quality applications that deliver meaningful value to users.`,
  chips: ['Systems thinker', 'Detail oriented', 'Clean code', 'Team player', 'Fast learner'],
}

export const skills = [
  { cat: 'Frontend', tags: ['Javascript', 'React', 'TypeScript', 'Tailwind CSS'], level: 'Advanced' },
  { cat: 'Backend',  tags: ['PHP', 'C#', 'Laravel', 'ASP.NET'],                  level: 'Advanced' },
  { cat: 'Mobile',   tags: ['Flutter', 'Dart', 'BLoC', 'Provider'],               level: 'Intermediate' },
  { cat: 'Database', tags: ['MySQL', 'PostgreSQL', 'Redis'],                       level: 'Proficient' },
  { cat: 'Workflow', tags: ['Git', 'CI/CD', 'Figma', 'Agile'],                    level: 'Everyday' },
]

export const projects = [
  {
    num: '01',
    title: 'BudgEx',
    stack: ['Flutter', 'React Typescript', 'ASP.NET'],
    desc: 'Budget Planning & Control — A platform for budget planning, budget realization tracking, variance analysis, and budget control across departments.',
    year: '2026',
    color: 'ind',
    githubUrl: '#',
    image: '',
  },
  {
    num: '02',
    title: 'DataKita ',
    stack: ['React', 'Typescript', 'Tailwind'],
    desc: 'Open Data Dashboard — A web based platform that aggregates public data from multiple APIs, including BMKG, World Bank, and disease.sh, and presents it through interactive and easy to understand visualizations.',
    year: '2026',
    color: 'pch',
    githubUrl: '#',
    image: '',
  },
  {
    num: '03',
    title: 'RoomRes',
    stack: ['ASP.NET', 'React Typescript', 'PostgreSQL'],
    desc: 'Campus Room Reservation System — A web application designed to simplify campus room booking management, enabling users to view room schedules, make reservation requests, track booking status, and efficiently coordinate room usage across campus facilities.',
    year: '2026',
    color: 'lav',
    githubUrl: '#',
    image: '',
  },
  {
    num: '04',
    title: 'Employee Management System',
    stack: ['Laravel', 'PHP', 'Javascript'],
    desc: 'Employee Management Application — A workforce management platform that simplifies employee records, attendance tracking, leave management, and administrative operations.',
    year: '2025',
    color: 'mint',
    githubUrl: '#',
    image: '',
  },
  {
    num: '05',
    title: 'Local MSMEs',
    stack: ['React', 'Tailwind CSS', 'Supabase'],
    desc: 'Local MSME Directory — A digital platform that helps users discover and connect with local MSMEs through business listings, category based browsing, and location based search features.',
    year: '2025',
    color: 'lav',
    githubUrl: '#',
    image: '',
  },
  {
    num: '06',
    title: 'Public Grievance System',
    stack: ['PHP', 'Javascript', 'CSS'],
    desc: 'Citizen Complaint Platform — A digital platform that enables citizens to report community issues and public service complaints efficiently. Users can submit reports, track their status, and receive updates, while administrators can manage, verify, and respond to complaints through a centralized system.',
    year: '2025',
    color: 'pch',
    githubUrl: '#',
    image: '',
  },
]